spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/Aliadan
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 9091

jwt:
  auth:
    converter:
      resource-id: aliadan-rest-api
      principle-attribute: preferred_username
